### ISSUE TITLE
添加插件后异常

### ISSUE THREAD

**Issue by GSCSDSUN** [theGravityLab/HyperaiShell#15]
| 名称 | 值 | 类型
-- | -- | -- | --
◢ | $exception | {"Could not load file or assembly 'Ac682.Hyperai.Clients.Mirai, Culture=neutral, PublicKeyToken=null'. 系统找不到指定的文件。":"Ac682.Hyperai.Clients.Mirai, Culture=neutral, PublicKeyToken=null"} | System.IO.FileNotFoundException

**Comment by d3ara1n** [comment]
默认配置文件里用的是我自己写的Ac682.Hyperai.Clients.Mirai适配器，要么自己写适配器，要么去对应仓库把它下载下来放进Plugins文件夹。配置方法文档里有写。
